"""Phase 6 + LLM: Skill Gap Agent.

Builds deterministic, provenance-annotated gap analyses on top of the persisted
Job Matching Agent results (Phases 4-5 outputs). Nothing is invented: each gap
item is derived from the shared engine's missing-skill lists plus the SkillGraph
for transferable/related skill context.

LLM integration: natural-language gap explanations, personalized learning advice,
and priority ranking are generated by a reasoning LLM for each gap item and
overall analysis. Falls back to deterministic text when LLM is unavailable.
"""

from __future__ import annotations

import json
import logging
import uuid

from sqlalchemy import select
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.skill2job_models import Skill2JobJob, Skill2JobJobMatch, Skill2JobSkillGap
from app.services.screening.matching_engine import MatchingEngine
from app.services.screening.skill_gap import SkillGapAnalyzer
from app.services.screening.skill_graph import SkillGraph
from app.skill2job.gap.schemas import (
    SkillGapAnalysis,
    SkillGapItem,
    SkillGapSummary,
    TeachingPlanStep,
)

logger = logging.getLogger(__name__)

GAP_VERSION = "skill2job-gap-7.0.0"


class SkillGapAgent:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ─── LLM helpers ──────────────────────────────────────────────────────

    async def _llm_chat(self, prompt: str, max_tokens: int = 1024) -> str | None:
        """Send a single-turn prompt to the LLM router; return content or None."""
        try:
            from app.ai_core.llm_client import LLMClient, LLMMessage

            client = LLMClient()
            response = await client.chat(
                messages=[LLMMessage(role="user", content=prompt)],
                temperature=0.4,
                max_tokens=max_tokens,
            )
            return response.content if response.content else None
        except Exception as exc:
            logger.warning("LLM call failed (falling back to deterministic): %s", exc)
            return None

    async def _generate_gap_explanation(
        self,
        skill: str,
        job_title: str,
        company: str,
        gap_kind: str,
        related_existing: list[str],
        transferable: list[str],
    ) -> str | None:
        """Generate a natural-language explanation for why this skill is a gap."""
        related_str = ", ".join(related_existing[:3]) if related_existing else "none"
        transfer_str = ", ".join(transferable[:3]) if transferable else "none"
        prompt = (
            f"You are a career guidance AI. A candidate is applying for "
            f"'{job_title}' at '{company}'. They are missing the skill '{skill}' "
            f"(classified as: {gap_kind}). Their related existing skills are: "
            f"[{related_str}]. Transferable skills they could leverage: [{transfer_str}].\n\n"
            f"Write a 2-3 sentence explanation of why this skill matters for the role "
            f"and how the candidate can bridge the gap. Be specific and actionable. "
            f"Return ONLY the explanation text, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=256)

    async def _generate_learning_advice(
        self,
        skill: str,
        job_title: str,
        related_existing: list[str],
    ) -> str | None:
        """Generate personalized learning advice for a specific skill gap."""
        existing_str = ", ".join(related_existing[:3]) if related_existing else "none"
        prompt = (
            f"You are a training advisor. A candidate wants to learn '{skill}' for "
            f"the role '{job_title}'. They already know: [{existing_str}].\n\n"
            f"Provide 1-2 sentences of specific, actionable learning advice. "
            f"Suggest the fastest path leveraging their existing knowledge. "
            f"Return ONLY the advice text, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=200)

    async def _generate_overall_summary(self, analyses: list[SkillGapAnalysis]) -> str | None:
        """Generate an overall LLM summary across all gap analyses."""
        if not analyses:
            return None
        job_summaries = []
        for a in analyses[:5]:
            job_summaries.append(
                f"- {a.job_title} at {a.company} (score {a.overall_score}/100): "
                f"missing {len(a.missing_required_skills)} required, "
                f"{len(a.missing_preferred_skills)} preferred skills"
            )
        all_missing = set()
        for a in analyses:
            all_missing.update(a.missing_required_skills)
        prompt = (
            f"You are a career intelligence analyst. A candidate was analyzed against "
            f"{len(analyses)} jobs:\n"
            + "\n".join(job_summaries)
            + f"\n\nAcross all jobs, these unique skills are missing: "
            f"{', '.join(sorted(all_missing)[:15])}.\n\n"
            f"Write a 3-4 sentence overall assessment of the candidate's biggest "
            f"skill gaps, their strongest areas, and the top 3 skills to prioritize "
            f"for maximum job market impact. Be specific and data-driven. "
            f"Return ONLY the assessment text, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=400)

    async def _generate_priority_ranking(
        self, analyses: list[SkillGapAnalysis]
    ) -> list[dict] | None:
        """Use LLM to rank gap skills by priority with reasoning."""
        if not analyses:
            return None
        skill_jobs: dict[str, list[str]] = {}
        for a in analyses:
            for skill in a.missing_required_skills:
                skill_jobs.setdefault(skill, []).append(f"{a.job_title} at {a.company}")
        skills_info = []
        for skill, jobs in sorted(skill_jobs.items(), key=lambda x: -len(x[1])):
            skills_info.append(f'"{skill}" (demanded by {len(jobs)} jobs: {", ".join(jobs[:3])})')
        prompt = (
            f"You are a career strategy AI. A candidate has these skill gaps, "
            f"sorted by job demand:\n"
            + "\n".join(skills_info[:12])
            + "\n\nReturn a JSON array (no markdown) of objects with keys: "
            '"skill", "rank" (1=highest), "reasoning" (1 sentence). '
            "Rank by: (1) number of jobs demanding it, (2) how quickly it can "
            "be learned given the candidate's existing skills, (3) salary impact. "
            "Return at most 10 items."
        )
        raw = await self._llm_chat(prompt, max_tokens=600)
        if not raw:
            return None
        try:
            cleaned = raw.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
            return json.loads(cleaned)
        except (json.JSONDecodeError, ValueError):
            logger.warning("LLM priority ranking response was not valid JSON")
            return None

    async def _ensure_matches(
        self,
        user_id: uuid.UUID,
        job_ids: list[str] | None,
        limit: int,
    ) -> list[Skill2JobJobMatch]:
        from app.skill2job.matching.agent import JobMatchingAgent

        wanted: list[str] = []
        if job_ids:
            for jid in job_ids:
                try:
                    wanted.append(str(uuid.UUID(jid)))
                except ValueError:
                    continue
            if not wanted:
                return []

        if wanted:
            existing = list(
                (
                    await self._session.execute(
                        select(Skill2JobJobMatch).where(
                            Skill2JobJobMatch.user_id == user_id,
                            Skill2JobJobMatch.job_id.in_(
                                [uuid.UUID(j) for j in wanted]
                            ),
                        )
                    )
                ).scalars().all()
            )
            have = {str(m.job_id) for m in existing}
            missing_ids = [j for j in wanted if j not in have]
            if missing_ids:
                await JobMatchingAgent(self._session).run_match(
                    user_id, job_ids=missing_ids, limit=len(missing_ids)
                )
            return list(
                (
                    await self._session.execute(
                        select(Skill2JobJobMatch).where(
                            Skill2JobJobMatch.user_id == user_id,
                            Skill2JobJobMatch.job_id.in_(
                                [uuid.UUID(j) for j in wanted]
                            ),
                        )
                    )
                ).scalars().all()
            )

        # no job_ids: analyze the candidate's best-scored persisted matches,
        # running matching over the catalog first if nothing is persisted.
        count = (
            await self._session.execute(
                select(Skill2JobJobMatch.id).where(
                    Skill2JobJobMatch.user_id == user_id
                ).limit(1)
            )
        ).scalars().first()
        if count is None:
            await JobMatchingAgent(self._session).run_match(
                user_id, job_ids=None, limit=10
            )
        rows = list(
            (
                await self._session.execute(
                    select(Skill2JobJobMatch)
                    .where(Skill2JobJobMatch.user_id == user_id)
                    .order_by(
                        Skill2JobJobMatch.overall_score.desc(),
                        Skill2JobJobMatch.created_at.desc(),
                    )
                    .limit(max(limit, 1))
                )
            ).scalars().all()
        )
        return rows

    async def analyze_profile(
        self,
        user_id: uuid.UUID,
        job_ids: list[str] | None = None,
        limit: int = 5,
    ) -> list[SkillGapAnalysis]:
        matches = await self._ensure_matches(user_id, job_ids, limit)
        job_map: dict[uuid.UUID, Skill2JobJob] = {}
        if matches:
            found = (
                await self._session.execute(
                    select(Skill2JobJob).where(
                        Skill2JobJob.id.in_([m.job_id for m in matches])
                    )
                )
            ).scalars().all()
            job_map = {j.id: j for j in found}

        analyses: list[SkillGapAnalysis] = []
        for match in matches:
            job = job_map.get(match.job_id)
            if job is None:
                continue
            analysis = await self._build_for_match(match, job)
            analyses.append(analysis)
            stmt = sqlite_insert(Skill2JobSkillGap).values(
                user_id=user_id,
                job_id=match.job_id,
                analysis=analysis.model_dump(mode="json"),
                analysis_version=GAP_VERSION,
            )
            stmt = stmt.on_conflict_do_update(
                index_elements=[
                    Skill2JobSkillGap.user_id,
                    Skill2JobSkillGap.job_id,
                ],
                set_={
                    "analysis": stmt.excluded.analysis,
                    "analysis_version": stmt.excluded.analysis_version,
                },
            )
            await self._session.execute(stmt)

        # Generate cross-job LLM insights after all analyses are built
        if analyses:
            llm_summary = await self._generate_overall_summary(analyses)
            llm_ranking = await self._generate_priority_ranking(analyses)
            if analyses:
                last = analyses[-1]
                analyses[-1] = last.model_copy(
                    update={
                        "llm_summary": llm_summary,
                        "llm_priority_ranking": llm_ranking or [],
                    }
                )

        await self._session.flush()
        return analyses

    async def _build_for_match(
        self, match: Skill2JobJobMatch, job: Skill2JobJob
    ) -> SkillGapAnalysis:
        missing_required = list(match.missing_required or [])
        missing_preferred = list(match.missing_preferred or [])
        required_skills = list(job.required_skills or [])

        gap_items: list[SkillGapItem] = []
        for skill in missing_required[:10]:
            evidence = (
                f"'{skill}' is a required skill for {job.title} at {job.company} "
                f"but is not present in your profile or perception history."
            )
            related = SkillGraph.get_related_skills(skill)
            existing_names = {s.lower() for s in list(match.matched_skills or [])}
            transferable = [
                r
                for r in related
                if r.lower() not in existing_names and r.lower() != skill.lower()
            ][:3]
            related_existing = [
                r
                for r in related
                if r.lower() in existing_names
            ][:3]

            # Deterministic classification
            normalized = SkillGraph.normalize(skill)
            present = normalized in {s.lower() for s in existing_names} or any(
                SkillGraph.are_synonyms(skill, v) for v in existing_names
            )
            gap_kind = "evidence_gap" if present else "skill_gap"

            # Generate LLM explanations (non-blocking, best-effort)
            llm_explanation = await self._generate_gap_explanation(
                skill=skill,
                job_title=job.title,
                company=job.company,
                gap_kind=gap_kind,
                related_existing=related_existing,
                transferable=transferable,
            )
            llm_learning_advice = await self._generate_learning_advice(
                skill=skill,
                job_title=job.title,
                related_existing=related_existing,
            )

            gap_items.append(
                SkillGapItem(
                    skill=skill,
                    role=job.title,
                    company=job.company,
                    evidence=evidence,
                    transferable=transferable,
                    related_existing=related_existing,
                    gap_kind=gap_kind,
                    llm_explanation=llm_explanation,
                    llm_learning_advice=llm_learning_advice,
                )
            )

        report = SkillGapAnalyzer.analyze(
            matched_skills=list(match.matched_skills or []),
            missing_required=missing_required,
            missing_preferred=missing_preferred,
            candidate_experience_years=0.0,
            required_experience_str=job.experience_required,
            candidate_degrees=[],
            required_education=job.education_required,
            candidate_certs=[],
            overall_score=match.overall_score,
        )
        return SkillGapAnalysis(
            job_id=str(match.job_id),
            job_title=job.title,
            company=job.company,
            overall_score=match.overall_score,
            missing_required_skills=missing_required,
            missing_preferred_skills=missing_preferred,
            gap_items=gap_items,
            experience_gap_description=report["experience_gap_description"],
            education_gap_description=report["education_gap_description"],
            certification_gap_description=report["certification_gap_description"],
            improvement_suggestions=report["improvement_suggestions"],
            interview_readiness_score=report["interview_readiness_score"],
            analysis_version=GAP_VERSION,
        )

    async def get_analysis(
        self, user_id: uuid.UUID, job_id: str | None = None
    ) -> list[SkillGapAnalysis]:
        stmt = select(Skill2JobSkillGap).where(Skill2JobSkillGap.user_id == user_id)
        if job_id:
            try:
                stmt = stmt.where(Skill2JobSkillGap.job_id == uuid.UUID(job_id))
            except ValueError:
                return []
        rows = (
            await self._session.execute(
                stmt.order_by(Skill2JobSkillGap.created_at.desc()).limit(50)
            )
        ).scalars().all()
        analyses = [SkillGapAnalysis(**r.analysis) for r in rows]

        # Enrich gap items with LLM explanations if not already present
        for analysis in analyses:
            enriched_items = []
            for item in analysis.gap_items:
                if item.llm_explanation is None:
                    llm_explanation = await self._generate_gap_explanation(
                        skill=item.skill,
                        job_title=item.role,
                        company=item.company,
                        gap_kind=item.gap_kind,
                        related_existing=item.related_existing,
                        transferable=item.transferable,
                    )
                    item = item.model_copy(update={"llm_explanation": llm_explanation})
                if item.llm_learning_advice is None:
                    llm_advice = await self._generate_learning_advice(
                        skill=item.skill,
                        job_title=item.role,
                        related_existing=item.related_existing,
                    )
                    item = item.model_copy(update={"llm_learning_advice": llm_advice})
                enriched_items.append(item)
            if any(i.llm_explanation is None for i in analysis.gap_items):
                analysis = analysis.model_copy(update={"gap_items": enriched_items})
        return analyses

    async def get_summary(self, user_id: uuid.UUID) -> SkillGapSummary:
        rows = (
            await self._session.execute(
                select(Skill2JobSkillGap).where(Skill2JobSkillGap.user_id == user_id)
            )
        ).scalars().all()
        analyses = [SkillGapAnalysis(**r.analysis) for r in rows]

        skill_demand: dict[str, dict] = {}
        for analysis in analyses:
            for skill in analysis.missing_required_skills:
                entry = skill_demand.setdefault(
                    skill.lower(),
                    {"skill": skill, "jobs": set(), "priority": "medium"},
                )
                entry["jobs"].add(f"{analysis.job_title} at {analysis.company}")

        gap_skills = [
            {
                "skill": v["skill"],
                "jobs_demanding": sorted(v["jobs"]),
                "count": len(v["jobs"]),
            }
            for v in skill_demand.values()
        ]
        gap_skills.sort(key=lambda g: (-g["count"], g["skill"]))

        teaching_plan: list[TeachingPlanStep] = []
        for entry in gap_skills[:8]:
            transferable: list[str] = []
            for analysis in analyses:
                for item in analysis.gap_items:
                    if item.skill.lower() == entry["skill"].lower():
                        transferable.extend(item.transferable)
                        break
            rationale: str
            if transferable:
                rationale = (
                    f"Learning '{entry['skill']}' while already being close to "
                    f"{', '.join(transferable[:2])} has the fastest skill-graph transfer."
                )
                priority = "high"
            else:
                rationale = (
                    f"'{entry['skill']}' is required by {entry['count']} "
                    f"matching opportunity/ies in your local market."
                )
                priority = "medium" if entry["count"] > 1 else "low"

            # Generate LLM-powered rationale and opportunity impact
            llm_rationale = await self._generate_teaching_rationale(
                skill=entry["skill"],
                jobs=entry["jobs_demanding"][:3],
                transferable=transferable,
                priority=priority,
            )
            opportunity_impact = await self._generate_opportunity_impact(
                skill=entry["skill"],
                job_count=entry["count"],
                jobs=entry["jobs_demanding"][:3],
            )

            teaching_plan.append(
                TeachingPlanStep(
                    skill=entry["skill"],
                    jobs_demanding=entry["jobs_demanding"][:3],
                    priority=priority,
                    rationale=rationale,
                    llm_rationale=llm_rationale,
                    opportunity_impact=opportunity_impact,
                )
            )

        # Generate overall LLM assessment
        llm_assessment = await self._generate_overall_summary(analyses) if analyses else None

        return SkillGapSummary(
            total_analyses=len(analyses),
            analyzed_jobs=len(analyses),
            gap_skills=gap_skills,
            teaching_plan=teaching_plan,
            llm_overall_assessment=llm_assessment,
        )

    async def _generate_teaching_rationale(
        self,
        skill: str,
        jobs: list[str],
        transferable: list[str],
        priority: str,
    ) -> str | None:
        """Generate LLM-powered rationale for why this skill is top priority."""
        jobs_str = ", ".join(jobs[:3])
        transfer_str = ", ".join(transferable[:2]) if transferable else "none"
        prompt = (
            f"You are a career strategy advisor. A candidate should learn '{skill}' "
            f"(priority: {priority}). It is demanded by these jobs: {jobs_str}. "
            f"Related skills they already have: [{transfer_str}].\n\n"
            f"In 1-2 sentences, explain WHY learning this specific skill will unlock "
            f"the most career opportunities. Be concrete about the impact. "
            f"Return ONLY the rationale text, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=200)

    async def _generate_opportunity_impact(
        self,
        skill: str,
        job_count: int,
        jobs: list[str],
    ) -> str | None:
        """Generate LLM-powered opportunity impact statement."""
        jobs_str = ", ".join(jobs[:3])
        prompt = (
            f"You are a job market analyst. Learning '{skill}' would make a candidate "
            f"eligible for {job_count} additional job(s): {jobs_str}.\n\n"
            f"In one sentence, quantify the career impact (e.g., 'unlocks roles at X, Y, Z "
            f"with typical salaries of N LPA'). Be specific and data-driven. "
            f"Return ONLY the impact statement, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=150)

    # ─── Phase 2 gap detail: skill gap vs evidence gap ────────────────────
    #
    # A missing required skill is either a genuine gap (absent from the
    # candidate's vocabulary) or an evidence gap (present in the profile or
    # perception vocabulary but weakly evidenced and never counted as a match).
    # We always say the accurate thing — never "you do not know X" for a skill
    # the candidate actually lists.

    async def get_gap_detail(
        self, user_id: uuid.UUID, job_id: str
    ) -> SkillGapAnalysis | None:
        analyses = await self.analyze_profile(user_id, job_ids=[job_id], limit=1)
        if not analyses:
            return None
        analysis = analyses[0]
        vocab = await self._candidate_vocabulary(user_id)
        enriched_items = []
        for item in analysis.gap_items:
            classified = self._classify_gap_item(item, vocab)
            # Add LLM explanation if not already present from analyze_profile
            if classified.llm_explanation is None:
                classified = classified.model_copy(
                    update={
                        "llm_explanation": await self._generate_gap_explanation(
                            skill=classified.skill,
                            job_title=classified.role,
                            company=classified.company,
                            gap_kind=classified.gap_kind,
                            related_existing=classified.related_existing,
                            transferable=classified.transferable,
                        )
                    }
                )
            if classified.llm_learning_advice is None:
                classified = classified.model_copy(
                    update={
                        "llm_learning_advice": await self._generate_learning_advice(
                            skill=classified.skill,
                            job_title=classified.role,
                            related_existing=classified.related_existing,
                        )
                    }
                )
            enriched_items.append(classified)
        filled = analysis.model_copy(update={"gap_items": enriched_items})
        return filled

    async def _candidate_vocabulary(self, user_id: uuid.UUID) -> set[str]:
        """Every skill name the candidate claims (profile + perceptions + tech)."""
        from app.skill2job.adapters.candidate_adapter import CandidateAdapter

        vocab: set[str] = set()
        try:
            adapter = CandidateAdapter(self._session)
            evidence = await adapter.get_skill_evidence_map(user_id)
            for key in evidence:
                vocab.add(SkillGraph.normalize(key))
        except Exception:
            pass
        return vocab

    @staticmethod
    def _classify_gap_item(item: SkillGapItem, vocab: set[str]) -> SkillGapItem:
        normalized = SkillGraph.normalize(item.skill)
        present = normalized in vocab or any(
            SkillGraph.are_synonyms(item.skill, v) for v in vocab
        )
        if present:
            gap_kind = "evidence_gap"
            evidence_note = (
                "You list this skill (or a close synonym) in your profile/resume "
                "vocabulary, but it carries weak evidence and was not counted as a "
                "match — close the evidence gap instead of learning from zero."
            )
            priority = "medium"
        else:
            gap_kind = "skill_gap"
            evidence_note = (
                "Absent from your profile skill and perception vocabulary — a "
                "genuine skill to acquire."
            )
            priority = "high"
        return item.model_copy(
            update={
                "gap_kind": gap_kind,
                "evidence_note": evidence_note,
                "priority": priority,
            }
        )