"""Phase 8 + LLM: Training Agent.

Builds a grounded learning program from the Skill Gap Agent's teaching plan.
Every module references a real, well-known provider resource (official docs /
certifications) from a curated registry; availability is explicitly
unverified so nothing is hallucinated.

LLM integration: natural-language recommendation reasons and opportunity-impact
statements are generated by a reasoning LLM for each training module and for
the overall plan. Falls back to deterministic text when LLM is unavailable.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Literal

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.skill2job_models import Skill2JobTrainingProgress
from app.skill2job.training.schemas import TrainingModule, TrainingPlan

logger = logging.getLogger(__name__)

TRAINING_VERSION = "skill2job-training-10.0.0"

# Trusted hosts. ``ALLOWED_RESOURCE_HOSTS`` is the closed set of domains the
# training agent may ever link to; ``VERIFIED_RESOURCE_HOSTS`` are domains whose
# linked pages were reviewed/known-stable and may carry ``source_status =
# "verified"``. Nothing outside these sets can ever be emitted, so hallucinated
# URLs are structurally impossible.
ALLOWED_RESOURCE_HOSTS: frozenset[str] = frozenset({
    "docs.python.org", "pythoninstitute.org", "pytorch.org", "scikit-learn.org",
    "www.postgresql.org", "dev.mysql.com", "learn.mongodb.com", "docs.docker.com",
    "kubernetes.io", "developer.hashicorp.com", "fastapi.tiangolo.com", "react.dev",
    "docs.djangoproject.com", "airflow.apache.org", "aws.amazon.com",
    "kafka.apache.org", "spark.apache.org", "docs.scala-lang.org",
    "doc.rust-lang.org", "go.dev", "nodejs.org", "training.linuxfoundation.org",
    "prometheus.io", "nptel.ac.in", "www.skillindiadigital.gov.in",
})

VERIFIED_RESOURCE_HOSTS: frozenset[str] = frozenset({
    "docs.python.org", "pytorch.org", "scikit-learn.org", "www.postgresql.org",
    "dev.mysql.com", "learn.mongodb.com", "docs.docker.com", "kubernetes.io",
    "developer.hashicorp.com", "fastapi.tiangolo.com", "react.dev",
    "docs.djangoproject.com", "airflow.apache.org", "aws.amazon.com",
    "kafka.apache.org", "spark.apache.org", "docs.scala-lang.org",
    "doc.rust-lang.org", "go.dev", "nodejs.org", "training.linuxfoundation.org",
    "prometheus.io", "nptel.ac.in", "www.skillindiadigital.gov.in",
})

_NPTEL_SOURCE = {
    "type": "course_catalog",
    "title": "NPTEL — free Indian institute-led online courses (IITs & IISc)",
    "provider": "NPTEL",
    "url": "https://nptel.ac.in/courses",
    "verified": True,
}

_SKILL_INDIA_SOURCE = {
    "type": "course_catalog",
    "title": "Skill India Digital Hub — national digital skills & upskilling platform",
    "provider": "Skill India",
    "url": "https://www.skillindiadigital.gov.in/",
    "verified": True,
}

# Curated, real learning resources keyed by canonical skill name (lowercase).
# ``verified`` records whether the linked page is a stable, known official
# source. Certification pages keep ``verified=False`` (enrollment/availability
# cannot be guaranteed); official documentation pages are ``verified=True``.
_RESOURCE_REGISTRY: dict[str, list[dict]] = {
    "python": [
        {"type": "official_docs", "title": "Python Official Tutorial", "provider": "python.org", "url": "https://docs.python.org/3/tutorial/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Programming in Python (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102066", "verified": True},
        {"type": "certification", "title": "PCEP — Certified Entry-Level Python Programmer", "provider": "Python Institute", "url": "https://pythoninstitute.org/pcep", "verified": False},
    ],
    "pytorch": [
        {"type": "official_docs", "title": "PyTorch Tutorials", "provider": "PyTorch", "url": "https://pytorch.org/tutorials/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Deep Learning (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102126", "verified": True},
    ],
    "scikit-learn": [
        {"type": "official_docs", "title": "scikit-learn User Guide & Tutorials", "provider": "scikit-learn", "url": "https://scikit-learn.org/stable/tutorial/index.html", "verified": True},
    ],
    "sql": [
        {"type": "official_docs", "title": "PostgreSQL Documentation", "provider": "PostgreSQL", "url": "https://www.postgresql.org/docs/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Database Management Systems (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106105153", "verified": True},
    ],
    "postgresql": [
        {"type": "official_docs", "title": "PostgreSQL Documentation", "provider": "PostgreSQL", "url": "https://www.postgresql.org/docs/", "verified": True},
    ],
    "mysql": [
        {"type": "official_docs", "title": "MySQL Reference Manual", "provider": "MySQL", "url": "https://dev.mysql.com/doc/", "verified": True},
    ],
    "mongodb": [
        {"type": "official_docs", "title": "MongoDB University", "provider": "MongoDB", "url": "https://learn.mongodb.com/", "verified": True},
    ],
    "docker": [
        {"type": "official_docs", "title": "Docker Get Started", "provider": "Docker", "url": "https://docs.docker.com/get-started/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Cloud Computing & Virtualization (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102115", "verified": True},
    ],
    "kubernetes": [
        {"type": "official_docs", "title": "Kubernetes Tutorials", "provider": "Kubernetes", "url": "https://kubernetes.io/docs/tutorials/", "verified": True},
    ],
    "terraform": [
        {"type": "official_docs", "title": "Terraform Tutorials", "provider": "HashiCorp", "url": "https://developer.hashicorp.com/terraform/tutorials", "verified": True},
    ],
    "fastapi": [
        {"type": "official_docs", "title": "FastAPI Tutorial", "provider": "FastAPI", "url": "https://fastapi.tiangolo.com/tutorial/", "verified": True},
    ],
    "react": [
        {"type": "official_docs", "title": "React Learn", "provider": "React", "url": "https://react.dev/learn", "verified": True},
    ],
    "django": [
        {"type": "official_docs", "title": "Django Tutorial", "provider": "Django", "url": "https://docs.djangoproject.com/en/stable/intro/tutorial01/", "verified": True},
    ],
    "airflow": [
        {"type": "official_docs", "title": "Apache Airflow Documentation", "provider": "Apache Airflow", "url": "https://airflow.apache.org/docs/", "verified": True},
    ],
    "aws": [
        {"type": "official_docs", "title": "AWS Training & Certification", "provider": "AWS", "url": "https://aws.amazon.com/training/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Cloud Computing (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102115", "verified": True},
    ],
    "kafka": [
        {"type": "official_docs", "title": "Apache Kafka Documentation", "provider": "Apache Kafka", "url": "https://kafka.apache.org/documentation/", "verified": True},
    ],
    "spark": [
        {"type": "official_docs", "title": "Apache Spark Documentation", "provider": "Apache Spark", "url": "https://spark.apache.org/docs/latest/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Big Data Computing (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102149", "verified": True},
    ],
    "scala": [
        {"type": "official_docs", "title": "Scala Tour", "provider": "Scala", "url": "https://docs.scala-lang.org/tour/tour-of-scala.html", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Programming in Scala (IIT Bombay)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102180", "verified": True},
    ],
    "rust": [
        {"type": "official_docs", "title": "The Rust Programming Language Book", "provider": "Rust", "url": "https://doc.rust-lang.org/book/", "verified": True},
    ],
    "go": [
        {"type": "official_docs", "title": "Go — Get Started", "provider": "golang.org", "url": "https://go.dev/doc/", "verified": True},
    ],
    "node.js": [
        {"type": "official_docs", "title": "Node.js Guide", "provider": "Node.js", "url": "https://nodejs.org/en/learn", "verified": True},
    ],
    "linux": [
        {"type": "official_docs", "title": "Linux Command Line Tutorial", "provider": "Linux Foundation", "url": "https://training.linuxfoundation.org/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Unix Programming (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102054", "verified": True},
    ],
    "prometheus": [
        {"type": "official_docs", "title": "Prometheus Documentation", "provider": "Prometheus", "url": "https://prometheus.io/docs/", "verified": True},
    ],
    "kafka (streams)": [
        {"type": "official_docs", "title": "Apache Kafka Documentation", "provider": "Apache Kafka", "url": "https://kafka.apache.org/documentation/", "verified": True},
    ],
    "java": [
        {"type": "official_docs", "title": "Java Tutorials", "provider": "Oracle", "url": "https://docs.oracle.com/javase/tutorial/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Programming in Java (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102052", "verified": True},
    ],
    "javascript": [
        {"type": "official_docs", "title": "MDN JavaScript Guide", "provider": "Mozilla", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", "verified": True},
    ],
    "machine learning": [
        {"type": "course_catalog", "title": "NPTEL — Machine Learning (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102066", "verified": True},
        {"type": "course_catalog", "title": "Coursera — Machine Learning by Andrew Ng", "provider": "Coursera", "url": "https://www.coursera.org/learn/machine-learning", "verified": True},
    ],
    "statistics": [
        {"type": "course_catalog", "title": "NPTEL — Introduction to Probability and Statistics", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/111107050", "verified": True},
    ],
    "deep learning": [
        {"type": "course_catalog", "title": "NPTEL — Deep Learning (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102126", "verified": True},
    ],
    "data analysis": [
        {"type": "official_docs", "title": "Pandas Getting Started", "provider": "Pandas", "url": "https://pandas.pydata.org/docs/getting_started/index.html", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Data Analytics with Python (IIT Roorkee)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106105147", "verified": True},
    ],
    "security": [
        {"type": "official_docs", "title": "OWASP Top Ten", "provider": "OWASP", "url": "https://owasp.org/www-project-top-ten/", "verified": True},
        {"type": "course_catalog", "title": "NPTEL — Information Security (IIT Kharagpur)", "provider": "NPTEL", "url": "https://nptel.ac.in/courses/106102084", "verified": True},
    ],
    "figma": [
        {"type": "official_docs", "title": "Figma Learning Resources", "provider": "Figma", "url": "https://help.figma.com/hc/en-us/categories/360002057614", "verified": True},
    ],
}


def _resources_for(skill: str) -> list[dict]:
    from urllib.parse import urlparse

    key = skill.lower().strip()
    if key in _RESOURCE_REGISTRY:
        resources = [
            {**r}
            for r in _RESOURCE_REGISTRY[key]
            if (not r.get("url")) or urlparse(r["url"]).netloc in ALLOWED_RESOURCE_HOSTS
        ]
        return _dedupe_resources(resources + [_NPTEL_SOURCE, _SKILL_INDIA_SOURCE])
    return [_NPTEL_SOURCE, _SKILL_INDIA_SOURCE]


def _dedupe_resources(resources: list[dict]) -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for r in resources:
        identity = r.get("url") or f"{r['type']}:{r['title']}"
        if identity in seen:
            continue
        seen.add(identity)
        out.append(r)
    return out


def _source_status(resource: dict) -> Literal["verified", "unverified"]:
    from urllib.parse import urlparse

    url = resource.get("url")
    if not url:
        return "unverified"
    host = urlparse(url).netloc
    if resource.get("verified") and host in VERIFIED_RESOURCE_HOSTS:
        return "verified"
    return "unverified"


def _status_for_url(url: str | None) -> Literal["verified", "unverified"]:
    from urllib.parse import urlparse

    if not url:
        return "unverified"
    if urlparse(url).netloc in VERIFIED_RESOURCE_HOSTS:
        return "verified"
    return "unverified"


class TrainingAgent:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ─── LLM helpers ──────────────────────────────────────────────────────

    async def _llm_chat(self, prompt: str, max_tokens: int = 512) -> str | None:
        """Send a single-turn prompt to the LLM router; return content or None."""
        try:
            from app.ai_core.llm_client import LLMClient, LLMMessage

            client = LLMClient()
            response = await client.chat(
                messages=[LLMMessage(role="user", content=prompt)],
                temperature=0.4,
                max_tokens=max_tokens,
            )
            return response.content if response.content else None
        except Exception as exc:
            logger.warning("LLM call failed (falling back to deterministic): %s", exc)
            return None

    async def _generate_recommendation_reason(
        self,
        skill: str,
        title: str,
        provider: str,
        is_free: bool,
        difficulty: str,
        gap_priority: str,
    ) -> str | None:
        """Generate LLM-powered recommendation reason for a training module."""
        cost_desc = "free" if is_free else "paid"
        prompt = (
            f"You are a training advisor. A candidate needs to learn '{skill}' "
            f"(gap priority: {gap_priority}). You recommend: '{title}' by {provider} "
            f"({cost_desc}, {difficulty} level).\n\n"
            f"In 1-2 sentences, explain why this specific resource is the best choice "
            f"for this candidate's career growth. Be concrete about what they'll gain. "
            f"Return ONLY the recommendation reason, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=200)

    async def _generate_opportunity_impact(
        self,
        skill: str,
        job_count: int,
    ) -> str | None:
        """Generate LLM-powered opportunity impact for learning this skill."""
        prompt = (
            f"You are a job market analyst. Learning '{skill}' would make a candidate "
            f"eligible for {job_count} more job(s) in their local market.\n\n"
            f"In one sentence, describe the career opportunity impact (roles unlocked, "
            f"salary range, market demand). Be specific to the Indian tech market. "
            f"Return ONLY the impact statement, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=150)

    async def _generate_plan_summary(
        self, modules: list[TrainingModule]
    ) -> str | None:
        """Generate LLM-powered summary for the overall training plan."""
        if not modules:
            return None
        skills = list({m.skill for m in modules})
        free_count = sum(1 for m in modules if m.is_free)
        prompt = (
            f"You are a career coach. A candidate has a training plan with "
            f"{len(modules)} modules covering: {', '.join(skills[:10])}. "
            f"{free_count} of {len(modules)} resources are free.\n\n"
            f"Write a 2-3 sentence summary of this training plan's value proposition. "
            f"Highlight the fastest wins and biggest ROI. "
            f"Return ONLY the summary text, no preamble."
        )
        return await self._llm_chat(prompt, max_tokens=300)

    async def plan_training(self, user_id: uuid.UUID, limit: int = 6) -> TrainingPlan:
        from app.skill2job.gap.agent import SkillGapAgent

        gap_agent = SkillGapAgent(self._session)
        summary = await gap_agent.get_summary(user_id)
        if not summary.gap_skills:
            await gap_agent.analyze_profile(user_id, limit=3)
            summary = await gap_agent.get_summary(user_id)

        # Build priority map from teaching plan for LLM context
        priority_map: dict[str, str] = {}
        for step in summary.teaching_plan:
            priority_map[step.skill.lower()] = step.priority

        # Count jobs demanding each skill for opportunity impact
        skill_job_count: dict[str, int] = {}
        for gs in summary.gap_skills:
            skill_job_count[gs["skill"].lower()] = gs.get("count", 1)

        modules: list[TrainingModule] = []
        for skill_entry in summary.gap_skills[: max(limit, 1)]:
            skill = skill_entry["skill"]
            resources = _resources_for(skill)
            core = [r for r in resources if r["type"] != "course_catalog"][:2]
            catalogs = [r for r in resources if r["type"] == "course_catalog"]
            gap_priority = priority_map.get(skill.lower(), "medium")
            job_count = skill_job_count.get(skill.lower(), 1)

            for resource in core + catalogs:
                # Generate LLM-powered recommendation reason
                llm_reason = await self._generate_recommendation_reason(
                    skill=skill,
                    title=resource["title"],
                    provider=resource["provider"],
                    is_free=resource.get("verified", False) or "free" in resource.get("title", "").lower(),
                    difficulty="intermediate",
                    gap_priority=gap_priority,
                )
                # Generate opportunity impact
                llm_impact = await self._generate_opportunity_impact(
                    skill=skill,
                    job_count=job_count,
                )
                modules.append(
                    TrainingModule(
                        module_key=f"{skill.lower().replace(' ', '_')}:{resource['type']}",
                        skill=skill,
                        title=resource["title"],
                        provider=resource["provider"],
                        url=resource.get("url"),
                        resource_type=resource["type"],
                        source_status=_source_status(resource),
                        llm_recommendation_reason=llm_reason,
                        llm_opportunity_impact=llm_impact,
                    )
                )

        # Generate overall plan summary
        llm_plan_summary = await self._generate_plan_summary(modules)

        return TrainingPlan(
            modules=modules,
            total_modules=len(modules),
            version=TRAINING_VERSION,
            llm_plan_summary=llm_plan_summary,
        )

    async def complete_module(
        self, user_id: uuid.UUID, module_key: str, status: str = "completed"
    ) -> dict:
        from app.skill2job.training.schemas import TrainingModule

        plan = await self.plan_training(user_id, limit=50)
        module = next((m for m in plan.modules if m.module_key == module_key), None)
        if module is None:
            return {"ok": False, "reason": "unknown module", "module_key": module_key}

        existing = (
            await self._session.execute(
                select(Skill2JobTrainingProgress).where(
                    Skill2JobTrainingProgress.user_id == user_id,
                    Skill2JobTrainingProgress.module_key == module_key,
                )
            )
        ).scalars().first()
        if existing:
            if status == "completed":
                existing.status = "completed"
                existing.completed_at = datetime.now(timezone.utc)
        else:
            self._session.add(
                Skill2JobTrainingProgress(
                    user_id=user_id,
                    module_key=module.module_key,
                    skill=module.skill,
                    title=module.title,
                    provider=module.provider,
                    url=module.url,
                    resource_type=module.resource_type,
                    status="completed" if status == "completed" else "in_progress",
                    completed_at=datetime.now(timezone.utc) if status == "completed" else None,
                )
            )
        await self._session.flush()
        return {"ok": True, "module_key": module_key, "status": status}

    async def get_progress(self, user_id: uuid.UUID) -> dict:
        rows = (
            await self._session.execute(
                select(Skill2JobTrainingProgress).where(
                    Skill2JobTrainingProgress.user_id == user_id
                )
            )
        ).scalars().all()
        return {
            "items": [
                {
                    "module_key": r.module_key,
                    "skill": r.skill,
                    "title": r.title,
                    "provider": r.provider,
                    "url": r.url,
                    "resource_type": r.resource_type,
                    "source_status": _status_for_url(r.url),
                    "status": r.status,
                    "completed_at": r.completed_at.isoformat() if r.completed_at else None,
                }
                for r in rows
            ],
            "total": len(rows),
        }