SKILL_DATABASE: dict[str, list[dict[str, str | list[str]]]] = {
    "programming_languages": [
        {"name": "python", "aliases": ["python3", "py", "cpython"]},
        {"name": "javascript", "aliases": ["js", "ecmascript", "es6", "es2015", "es2020"]},
        {"name": "typescript", "aliases": ["ts", "typescript"]},
        {"name": "java", "aliases": ["java8", "java11", "java17", "j2ee"]},
        {"name": "c#", "aliases": ["csharp", "c sharp", "dotnet", ".net", "net"]},
        {"name": "c++", "aliases": ["cpp", "cplusplus", "c plus plus"]},
        {"name": "c", "aliases": ["c language", "ansi c"]},
        {"name": "go", "aliases": ["golang", "go lang"]},
        {"name": "rust", "aliases": ["rust-lang", "rustlang"]},
        {"name": "kotlin", "aliases": ["kotlin"]},
        {"name": "swift", "aliases": ["swift"]},
        {"name": "ruby", "aliases": ["ruby", "ruby on rails", "ror"]},
        {"name": "php", "aliases": ["php"]},
        {"name": "scala", "aliases": ["scala"]},
        {"name": "perl", "aliases": ["perl", "perl5"]},
        {"name": "r", "aliases": ["r language", "rstats"]},
        {"name": "dart", "aliases": ["dart", "dart lang"]},
        {"name": "elixir", "aliases": ["elixir"]},
        {"name": "haskell", "aliases": ["haskell"]},
        {"name": "lua", "aliases": ["lua"]},
        {"name": "shell", "aliases": ["bash", "zsh", "sh", "shell script", "posix"]},
        {"name": "powershell", "aliases": ["pwsh", "ps1"]},
        {"name": "sql", "aliases": ["pl/sql", "tsql", "transact-sql", "mysql", "postgresql", "postgres", "sqlite", "mssql"]},
        {"name": "graphql", "aliases": ["gql", "graphql"]},
        {"name": "assembly", "aliases": ["asm", "assembly language"]},
        {"name": "objective-c", "aliases": ["objc", "objective c", "obj-c"]},
        {"name": "groovy", "aliases": ["groovy"]},
        {"name": "clojure", "aliases": ["clojure", "clj"]},
        {"name": "erlang", "aliases": ["erlang"]},
    ],
    "frontend": [
        {"name": "react", "aliases": ["reactjs", "react.js", "react js"]},
        {"name": "vue", "aliases": ["vuejs", "vue.js", "vue js", "vue2", "vue3"]},
        {"name": "angular", "aliases": ["angularjs", "angular.io", "angular 2+"]},
        {"name": "svelte", "aliases": ["svelte", "sveltekit"]},
        {"name": "html", "aliases": ["html5", "html"]},
        {"name": "css", "aliases": ["css3", "css"]},
        {"name": "scss", "aliases": ["sass", "scss"]},
        {"name": "less", "aliases": ["less css"]},
        {"name": "tailwind", "aliases": ["tailwind css", "tailwindcss"]},
        {"name": "bootstrap", "aliases": ["bootstrap4", "bootstrap5", "bootstrap"]},
        {"name": "material ui", "aliases": ["mui", "material-ui", "material design"]},
        {"name": "chakra ui", "aliases": ["chakra", "chakra-ui"]},
        {"name": "ant design", "aliases": ["antd", "ant design"]},
        {"name": "redux", "aliases": ["redux", "redux toolkit", "rtk"]},
        {"name": "webpack", "aliases": ["webpack"]},
        {"name": "vite", "aliases": ["vite", "vitejs"]},
        {"name": "next.js", "aliases": ["nextjs", "next", "next.js"]},
        {"name": "nuxt", "aliases": ["nuxtjs", "nuxt.js"]},
        {"name": "gatsby", "aliases": ["gatsby", "gatsbyjs"]},
        {"name": "jquery", "aliases": ["jquery", "$"]},
        {"name": "d3.js", "aliases": ["d3", "d3js"]},
        {"name": "chart.js", "aliases": ["chartjs", "chart.js"]},
        {"name": "three.js", "aliases": ["threejs", "three"]},
        {"name": "astro", "aliases": ["astro", "astrojs"]},
        {"name": "remix", "aliases": ["remix", "remix.run"]},
        {"name": "styled-components", "aliases": ["styled components", "styled components"]},
    ],
    "backend": [
        {"name": "django", "aliases": ["django", "django rest framework", "drf"]},
        {"name": "flask", "aliases": ["flask"]},
        {"name": "fastapi", "aliases": ["fastapi", "fast api"]},
        {"name": "express", "aliases": ["express", "expressjs", "express.js", "express js"]},
        {"name": "spring boot", "aliases": ["spring", "spring boot", "spring framework"]},
        {"name": "asp.net", "aliases": ["asp.net", "aspnet", ".net core", "dotnet core"]},
        {"name": "node.js", "aliases": ["node", "nodejs", "node.js", "node js"]},
        {"name": "deno", "aliases": ["deno", "deno.js"]},
        {"name": "laravel", "aliases": ["laravel"]},
        {"name": "ruby on rails", "aliases": ["rails", "ror", "ruby on rails"]},
        {"name": "gin", "aliases": ["gin", "gin gonic"]},
        {"name": "echo", "aliases": ["echo framework"]},
        {"name": "fiber", "aliases": ["fiber", "gofiber"]},
        {"name": "actix", "aliases": ["actix", "actix-web"]},
        {"name": "rocket", "aliases": ["rocket framework"]},
        {"name": "ktor", "aliases": ["ktor"]},
        {"name": "nestjs", "aliases": ["nest", "nestjs", "nest.js"]},
    ],
    "databases": [
        {"name": "postgresql", "aliases": ["postgresql", "postgres", "psql"]},
        {"name": "mysql", "aliases": ["mysql", "mariadb"]},
        {"name": "mongodb", "aliases": ["mongo", "mongodb", "mongoose"]},
        {"name": "redis", "aliases": ["redis"]},
        {"name": "elasticsearch", "aliases": ["elastic", "elastic search", "es"]},
        {"name": "sqlite", "aliases": ["sqlite", "sqlite3"]},
        {"name": "dynamodb", "aliases": ["dynamo db", "dynamodb", "aws dynamodb"]},
        {"name": "cassandra", "aliases": ["cassandra", "cql"]},
        {"name": "couchbase", "aliases": ["couchbase"]},
        {"name": "firebase", "aliases": ["firebase", "firestore", "firebase realtime database"]},
        {"name": "neo4j", "aliases": ["neo4j", "neo4j"]},
        {"name": "clickhouse", "aliases": ["clickhouse"]},
        {"name": "influxdb", "aliases": ["influx db", "influxdb"]},
        {"name": "oracle", "aliases": ["oracle db", "oracle database"]},
        {"name": "sql server", "aliases": ["mssql", "sql server", "microsoft sql server"]},
        {"name": "ibm db2", "aliases": ["db2", "ibm db2"]},
        {"name": "supabase", "aliases": ["supabase"]},
    ],
    "cloud_devops": [
        {"name": "aws", "aliases": ["amazon web services", "aws", "ec2", "s3", "lambda"]},
        {"name": "azure", "aliases": ["azure", "microsoft azure"]},
        {"name": "gcp", "aliases": ["gcp", "google cloud", "google cloud platform"]},
        {"name": "docker", "aliases": ["docker", "docker compose", "containerization"]},
        {"name": "kubernetes", "aliases": ["k8s", "kubernetes", "kube"]},
        {"name": "terraform", "aliases": ["terraform", "iac"]},
        {"name": "ansible", "aliases": ["ansible"]},
        {"name": "jenkins", "aliases": ["jenkins", "jenkins ci"]},
        {"name": "github actions", "aliases": ["gha", "github actions", "actions"]},
        {"name": "gitlab ci", "aliases": ["gitlab ci", "gitlab-ci", "gitlab ci/cd"]},
        {"name": "circleci", "aliases": ["circle ci", "circleci"]},
        {"name": "helm", "aliases": ["helm", "helm charts"]},
        {"name": "prometheus", "aliases": ["prometheus"]},
        {"name": "grafana", "aliases": ["grafana"]},
        {"name": "nginx", "aliases": ["nginx", "nginx"]},
        {"name": "cloudflare", "aliases": ["cloudflare", "cf"]},
        {"name": "pulumi", "aliases": ["pulumi"]},
        {"name": "vagrant", "aliases": ["vagrant"]},
        {"name": "consul", "aliases": ["consul", "hashicorp consul"]},
        {"name": "vault", "aliases": ["vault", "hashicorp vault"]},
    ],
    "data_ml": [
        {"name": "pandas", "aliases": ["pandas"]},
        {"name": "numpy", "aliases": ["numpy", "np"]},
        {"name": "scikit-learn", "aliases": ["sklearn", "scikit learn", "scikit-learn"]},
        {"name": "tensorflow", "aliases": ["tensorflow", "tf", "tf2"]},
        {"name": "pytorch", "aliases": ["pytorch", "torch"]},
        {"name": "keras", "aliases": ["keras"]},
        {"name": "matplotlib", "aliases": ["matplotlib", "mpl"]},
        {"name": "seaborn", "aliases": ["seaborn"]},
        {"name": "plotly", "aliases": ["plotly", "plotly dash"]},
        {"name": "jupyter", "aliases": ["jupyter", "jupyter notebook", "jupyter lab"]},
        {"name": "spark", "aliases": ["apache spark", "pyspark", "spark"]},
        {"name": "hadoop", "aliases": ["hadoop", "hdfs"]},
        {"name": "airflow", "aliases": ["airflow", "apache airflow"]},
        {"name": "mlflow", "aliases": ["mlflow"]},
        {"name": "opencv", "aliases": ["opencv", "cv2"]},
        {"name": "nltk", "aliases": ["nltk"]},
        {"name": "spacy", "aliases": ["spacy", "spaCy"]},
        {"name": "hugging face", "aliases": ["huggingface", "hf", "transformers"]},
        {"name": "langchain", "aliases": ["langchain", "lc"]},
        {"name": "llama", "aliases": ["llama", "llama2", "llama3"]},
        {"name": "openai", "aliases": ["openai", "gpt", "chatgpt", "gpt-4"]},
        {"name": "xgboost", "aliases": ["xgboost", "xgb"]},
        {"name": "lightgbm", "aliases": ["lightgbm", "lgbm"]},
        {"name": "tableau", "aliases": ["tableau"]},
        {"name": "power bi", "aliases": ["powerbi", "power bi", "power bi"]},
        {"name": "looker", "aliases": ["looker", "looker studio"]},
        {"name": "kafka", "aliases": ["kafka", "apache kafka"]},
        {"name": "flink", "aliases": ["flink", "apache flink"]},
    ],
    "tools": [
        {"name": "git", "aliases": ["git", "github", "gitlab", "bitbucket"]},
        {"name": "jira", "aliases": ["jira", "jira"]},
        {"name": "confluence", "aliases": ["confluence"]},
        {"name": "slack", "aliases": ["slack"]},
        {"name": "figma", "aliases": ["figma"]},
        {"name": "sketch", "aliases": ["sketch"]},
        {"name": "adobe xd", "aliases": ["adobe xd", "xd"]},
        {"name": "photoshop", "aliases": ["photoshop", "ps"]},
        {"name": "illustrator", "aliases": ["illustrator", "ai"]},
        {"name": "postman", "aliases": ["postman"]},
        {"name": "swagger", "aliases": ["swagger", "openapi"]},
        {"name": "kibana", "aliases": ["kibana"]},
        {"name": "sentry", "aliases": ["sentry"]},
        {"name": "datadog", "aliases": ["datadog"]},
        {"name": "new relic", "aliases": ["new relic", "newrelic"]},
        {"name": "splunk", "aliases": ["splunk"]},
        {"name": "unity", "aliases": ["unity", "unity3d"]},
        {"name": "unreal engine", "aliases": ["unreal", "unreal engine"]},
        {"name": "blender", "aliases": ["blender"]},
        {"name": "trello", "aliases": ["trello"]},
        {"name": "notion", "aliases": ["notion"]},
        {"name": "asana", "aliases": ["asana"]},
        {"name": "monday.com", "aliases": ["monday.com", "monday"]},
        {"name": "linear", "aliases": ["linear"]},
        {"name": "clickup", "aliases": ["clickup"]},
        {"name": "grpc", "aliases": ["grpc", "protobuf"]},
        {"name": "rabbitmq", "aliases": ["rabbitmq", "rabbit"]},
        {"name": "celery", "aliases": ["celery"]},
    ],
    "soft_skills": [
        {"name": "leadership", "aliases": ["leadership", "team lead", "tech lead"]},
        {"name": "communication", "aliases": ["communication", "verbal communication", "written communication"]},
        {"name": "teamwork", "aliases": ["teamwork", "collaboration", "team player"]},
        {"name": "problem solving", "aliases": ["problem solving", "analytical", "critical thinking"]},
        {"name": "project management", "aliases": ["project management", "project mgmt"]},
        {"name": "agile", "aliases": ["agile", "scrum", "kanban", "sprint"]},
        {"name": "time management", "aliases": ["time management", "prioritization", "organization"]},
        {"name": "mentoring", "aliases": ["mentoring", "mentorship", "coaching"]},
        {"name": "presentation", "aliases": ["presentation", "public speaking"]},
        {"name": "negotiation", "aliases": ["negotiation", "conflict resolution"]},
        {"name": "decision making", "aliases": ["decision making", "strategic thinking"]},
        {"name": "adaptability", "aliases": ["adaptability", "flexibility"]},
        {"name": "creativity", "aliases": ["creativity", "creative thinking", "innovation"]},
        {"name": "emotional intelligence", "aliases": ["emotional intelligence", "eq"]},
        {"name": "cross-functional", "aliases": ["cross-functional", "cross team collaboration"]},
    ],
    "testing": [
        {"name": "pytest", "aliases": ["pytest", "py.test"]},
        {"name": "junit", "aliases": ["junit", "junit5"]},
        {"name": "jest", "aliases": ["jest"]},
        {"name": "mocha", "aliases": ["mocha", "mocha.js"]},
        {"name": "cypress", "aliases": ["cypress", "cypress.io"]},
        {"name": "playwright", "aliases": ["playwright"]},
        {"name": "selenium", "aliases": ["selenium", "selenium webdriver"]},
        {"name": "robot framework", "aliases": ["robot", "robot framework"]},
        {"name": "testng", "aliases": ["testng"]},
        {"name": "rspec", "aliases": ["rspec"]},
        {"name": "mockito", "aliases": ["mockito"]},
        {"name": "unittest", "aliases": ["unittest", "pyunit"]},
        {"name": "tdd", "aliases": ["tdd", "test driven development"]},
        {"name": "bdd", "aliases": ["bdd", "behavior driven development"]},
        {"name": "cucumber", "aliases": ["cucumber", "gherkin"]},
        {"name": "postman", "aliases": ["postman", "newman"]},
        {"name": "locust", "aliases": ["locust"]},
        {"name": "k6", "aliases": ["k6", "k6.io"]},
        {"name": "sonarqube", "aliases": ["sonar", "sonarqube"]},
    ],
    "security": [
        {"name": "owasp", "aliases": ["owasp", "owasp top 10"]},
        {"name": "penetration testing", "aliases": ["pen testing", "pentest", "penetration testing"]},
        {"name": "oauth", "aliases": ["oauth", "oauth2", "oauth 2.0"]},
        {"name": "jwt", "aliases": ["jwt", "json web token"]},
        {"name": "ssl/tls", "aliases": ["ssl", "tls", "https", "certificates"]},
        {"name": "encryption", "aliases": ["encryption", "aes", "rsa", "cryptography"]},
        {"name": "saml", "aliases": ["saml", "sso"]},
        {"name": "ldap", "aliases": ["ldap", "active directory"]},
        {"name": "firewall", "aliases": ["firewall", "waf"]},
        {"name": "siem", "aliases": ["siem", "security information"]},
        {"name": "vulnerability assessment", "aliases": ["vulnerability assessment", "vapt"]},
        {"name": "burp suite", "aliases": ["burp", "burp suite", "burpsuite"]},
        {"name": "kali linux", "aliases": ["kali", "kali linux"]},
        {"name": "metasploit", "aliases": ["metasploit"]},
        {"name": "nmap", "aliases": ["nmap"]},
        {"name": "wireshark", "aliases": ["wireshark"]},
    ],
}


def build_skill_lookup() -> dict[str, str]:
    lookup: dict[str, str] = {}
    for category, skills in SKILL_DATABASE.items():
        for skill in skills:
            name: str = skill["name"]
            lookup[name.lower()] = name
            for alias in skill["aliases"]:
                lookup[alias.lower().strip()] = name
    return lookup


SKILL_LOOKUP = build_skill_lookup()


def get_all_skill_names() -> list[str]:
    return sorted({s["name"] for items in SKILL_DATABASE.values() for s in items})
